name: External contribution guidelines

on:
  pull_request:
    types: [opened, reopened]

env:
  DRY_RUN: false

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  comment-external-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Comment External Contributor PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          echo "Commenting new external PR: $PR"
          if [[ $DRY_RUN == "false" ]]; then
            gh pr edit $PR --add-label 'external contribution :star:'
            gh pr comment $PR --body 'Hi, thank you for your contribution.'
          fi
