name: External contribution guidelines

on:
  issues:
    types: 
      - opened
      - reopened

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORGANIZATION: bootCorp
  DRY_RUN: false

jobs:
  comment-external-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Get organization members
        env:
          CONTRIBUTOR: ${{ github.event.issue.user.login }}
        run: |
           gh api graphql \
            --raw-field org="$ORGANIZATION" \
            --raw-field query='
              query($org: String!, $cursor: String) {
                organization(login: $org) {
                  membersWithRole(first: 100, after: $cursor) {
                    pageInfo {
                      hasNextPage,
                      endCursor
                    }
                    nodes {
                      login
                    }
                  }
                }
              }' > org_members.json
            echo 'CONTRIBUTOR_IS_ORG_MEMBER='$(jq '.data.organization.membersWithRole | any(.nodes[].login; . == "$CONTRIBUTOR")' org_members.json) >> $GITHUB_ENV
    
      - name: Comment on external contribution PR
        if: ${{ env.CONTRIBUTOR_IS_ORG_MEMBER == 'false' }}
        env:
          PR: ${{ github.event.issue.html_url }}
        run: |
          echo "Commenting new external PR: $PR"
          if [[ $DRY_RUN == "false" ]]; then
            gh pr edit $PR --add-label "external contribution :star:"
            gh pr comment $PR --body "Hi, thank you for your contribution."
          fi
