name: External contribution guidelines

on:
  pull_request_target:
    types: 
      - opened
      - reopened

env:
  ORGANIZATION: bootCorp
  DRY_RUN: false

jobs:
  comment-external-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Get organization members
        env:
          GH_TOKEN: ${{ secrets.READ_ORG }}
          CONTRIBUTOR: ${{ github.event.pull_request.user.login }}
        run: |
           gh api graphql \
            --raw-field org="$ORGANIZATION" \
            --raw-field query='
              query($org: String!, $cursor: String) {
                organization(login: $org) {
                  membersWithRole(first: 100, after: $cursor) {
                    pageInfo {
                      hasNextPage,
                      endCursor
                    }
                    nodes {
                      login
                    }
                  }
                }
              }' > org_members.json
            echo 'CONTRIBUTOR_IS_ORG_MEMBER='"$(jq '.data.organization.membersWithRole | any(.nodes[].login; . == "$CONTRIBUTOR")' org_members.json)" >> $GITHUB_ENV
            echo "MEMBERS: $(jq '.data.organization.membersWithRole | any(.nodes[].login; . == "$CONTRIBUTOR")' org_members.json)"
      - name: Comment on external contribution PR
        if: ${{ env.CONTRIBUTOR_IS_ORG_MEMBER == "false" }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          echo "aa $CONTRIBUTOR_IS_ORG_MEMBER"
          echo "Commenting new external PR: $PR"
          if [[ $DRY_RUN == "false" ]]; then
            gh pr edit $PR --add-label "external contribution :star:"
            gh pr comment $PR --body "Hi, thank you for your contribution."
          fi
